micronaut:
  application:
    name: userAndAuthentication

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

#google:
#  clientid: "597932872393-f75kmuhqikket5k7kv31irvgr8ghh82j.apps.googleusercontent.com"

#jwt:
#   secret: "KCvxfSSBImPIqQrYOBvr1sGOHFeEfvMsQcqX3eh6fKM="

r2dbc:
  datasources:
    default:
      url: r2dbc:mariadb://localhost:3307/omediapoint
      username: root
